export enum Field {
  CONTINENT_NAME = 'CONTINENT_NAME',
  REGION_NAME = 'REGION_NAME',
  COUNTRY_NAME = 'COUNTRY_NAME',
  COUNTRY_YEAR = 'COUNTRY_YEAR',
  COUNTRY_POPULATION = 'COUNTRY_POPULATION',
  COUNTRY_GDP = 'COUNTRY_GDP',
}
